import type { NextPage } from "next";
import Head from "next/head";
import ListContainer from "../components/ListContainer";
import axios from "axios";


const Home: NextPage = ({data} : any) => {


  return (
    <>
      <Head>
        <title>Stats of the day</title>
        <meta name="Football stats and match information for the next Premier league fixtures." content="Generated by create-t3-app" />
        <link rel="icon" href="/football-icon.jpeg" />
      </Head>
      <ListContainer fixtures={data} />
    </>
  );
};

export default Home;

export async function getStaticProps() {

  const options = {
    method: 'GET',
    url: 'https://api-football-v1.p.rapidapi.com/v3/fixtures',
    params: {league: '39', next: '10'},
    headers: {
      'X-RapidAPI-Key': 'cfb46f14e4mshc29e8bb6b4d31c3p18e819jsne9c885907854',
      'X-RapidAPI-Host': 'api-football-v1.p.rapidapi.com'
    }
  };


  const data = await axios.request(options).then(function (response) {
    return response.data
  }).catch(function (error) {
    console.error(error);
  });

  

  return {
    props: { data }  // will be passed to the page component as props
  };
}
