import type { NextPage } from "next";
import Head from "next/head";
import ListContainer from "../components/fixtureinformation/ListContainer";
import axios from "axios";

const Home: NextPage = ({ data }: any) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListContainer fixtures={data} />
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const res = await axios.get("http://localhost:3000/api/test");
  const data = res.data;

  return {
    props: { data }, // will be passed to the page component as props
  };
}
