import type { NextPage } from "next";
import Head from "next/head";
import { useTestGetFixtures } from "../api/useTestGetFixtures";
import ListContainer from "../components/ListContainer";

const Home: NextPage = () => {
  const data = useTestGetFixtures()
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ListContainer data = {data}/>
    </>
  );
};

export default Home;
